name: macos_test 

on:
  workflow_dispatch

jobs:
  install-macos:
    runs-on: macos-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install OpenSCAD
        run: brew install openscad

      - name: Install jupyterscad
        run: pip install --quiet --upgrade jupyterscad

      - name: Render stl
        run: python -c "from jupyterscad import render_stl; render_stl('cube([3,3,3]);', 'output.stl')"

