name: macos_test 

on:
  workflow_dispatch

jobs:
  install-macos:
    runs-on: macos-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Download and Install OpenSCAD
        run: brew install openscad

      - name: Run
        run: |
          pip install --quiet --upgrade jupyterscad
          python -c "from jupyterscad import render_stl; render_stl('cube([3,3,3]);', 'output.stl'); print('success')"

