name: windows-test

on:
  workflow_dispatch

jobs:
  install-windows:
    runs-on: windows-latest
    steps:
      - name: Download OpenSCAD
        shell: pwsh
        run: |
          (New-Object System.Net.WebClient).DownloadFile('https://files.openscad.org/OpenSCAD-2021.01-x86-32-Installer.exe', 'OpenSCAD-2021.01-x86-32-Installer.exe')
      - name: Install OpenSCAD
        run: OpenSCAD-2021.01-x86-32-Installer.exe

