name: windows-test

jobs:
  install-windows:
    runs-on: windows-latest
    steps:
      - name: Install OpenSCAD
        shell: pwsh
        run: 
      - name: Run the scripts
        run: |
          (New-Object System.Net.WebClient).DownloadFile('https://files.openscad.org/OpenSCAD-2021.01-x86-32-Installer.exe', 'OpenSCAD-2021.01-x86-32-Installer.exe')
          .\ OpenSCAD-2021.01-x86-32-Installer.exe

