name: windows-test

on:
  workflow_dispatch

jobs:
  install-windows:
    runs-on: windows-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Download and Install OpenSCAD
        shell: pwsh
        run: |
          (New-Object System.Net.WebClient).DownloadFile('https://files.openscad.org/OpenSCAD-2021.01-x86-32-Installer.exe', 'OpenSCAD-2021.01-x86-32-Installer.exe')
          .\OpenSCAD-2021.01-x86-32-Installer.exe

      - name: Run
        run: |
          pip install --upgrade jupyterscad
          python -c "from jupyterscad import render_stl; render_stl('cube([3,3,3]);', 'output.stl')"

