name: windows-test

on:
  workflow_dispatch

jobs:
  install-windows:
    runs-on: windows-latest
    steps:
      - name: Download and Install OpenSCAD
        shell: pwsh
        run: |
          (New-Object System.Net.WebClient).DownloadFile('https://files.openscad.org/OpenSCAD-2021.01-x86-64-Installer.exe', 'OpenSCAD-Installer.exe')
          .\OpenSCAD--Installer.exe

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Find OpenSCAD
        run: python -c "from shutil import which; print(which('C:\\Program Files\\OpenSCAD\\openscad.exe'))"
